// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1MaRi5vyWsJ1bnpPE3sR68REzWmI7TQ',
    appId: '1:720949519230:web:330a0b74dfdb396f73c92f',
    messagingSenderId: '720949519230',
    projectId: 'olxm-3b58c',
    authDomain: 'olxm-3b58c.firebaseapp.com',
    storageBucket: 'olxm-3b58c.appspot.com',
    measurementId: 'G-XV5G0CMGQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaw5zSRwDXACa_3Z5rk0-rtjh-0wqW5Og',
    appId: '1:720949519230:android:b600eee7b989b0cd73c92f',
    messagingSenderId: '720949519230',
    projectId: 'olxm-3b58c',
    storageBucket: 'olxm-3b58c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5xxNK-JWtoUgis5rwgn6q0zC_3XTs5M',
    appId: '1:720949519230:ios:b0708929c8b7a4d873c92f',
    messagingSenderId: '720949519230',
    projectId: 'olxm-3b58c',
    storageBucket: 'olxm-3b58c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5xxNK-JWtoUgis5rwgn6q0zC_3XTs5M',
    appId: '1:720949519230:ios:b0708929c8b7a4d873c92f',
    messagingSenderId: '720949519230',
    projectId: 'olxm-3b58c',
    storageBucket: 'olxm-3b58c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1MaRi5vyWsJ1bnpPE3sR68REzWmI7TQ',
    appId: '1:720949519230:web:f23ff9f8b3924f2973c92f',
    messagingSenderId: '720949519230',
    projectId: 'olxm-3b58c',
    authDomain: 'olxm-3b58c.firebaseapp.com',
    storageBucket: 'olxm-3b58c.appspot.com',
    measurementId: 'G-27ZQBX32B7',
  );
}
