// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3lt--aeyZXxXupgCaPwRCayFwVwf0iQ',
    appId: '1:349310092925:web:27d91849908aca92e69314',
    messagingSenderId: '349310092925',
    projectId: 'olxm-d8fc0',
    authDomain: 'olxm-d8fc0.firebaseapp.com',
    storageBucket: 'olxm-d8fc0.appspot.com',
    measurementId: 'G-D1SV20FEDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LsMxlVqLw5Jj05_-TQOHW5Zp9R1elRA',
    appId: '1:349310092925:android:b70baf099defea9de69314',
    messagingSenderId: '349310092925',
    projectId: 'olxm-d8fc0',
    storageBucket: 'olxm-d8fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXvW5xPGpZVAowGULk2SlOVpLdtKXCyE0',
    appId: '1:349310092925:ios:7a584d65f4426a1ae69314',
    messagingSenderId: '349310092925',
    projectId: 'olxm-d8fc0',
    storageBucket: 'olxm-d8fc0.appspot.com',
    iosBundleId: 'com.example.olxmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXvW5xPGpZVAowGULk2SlOVpLdtKXCyE0',
    appId: '1:349310092925:ios:7a584d65f4426a1ae69314',
    messagingSenderId: '349310092925',
    projectId: 'olxm-d8fc0',
    storageBucket: 'olxm-d8fc0.appspot.com',
    iosBundleId: 'com.example.olxmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq3lt--aeyZXxXupgCaPwRCayFwVwf0iQ',
    appId: '1:349310092925:web:238ef6673bc8a53ae69314',
    messagingSenderId: '349310092925',
    projectId: 'olxm-d8fc0',
    authDomain: 'olxm-d8fc0.firebaseapp.com',
    storageBucket: 'olxm-d8fc0.appspot.com',
    measurementId: 'G-8XKLPY845T',
  );
}
