// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3m9XSqBhyo8x5bgUAytQOKVFlUmhStKY',
    appId: '1:1070806981009:web:b1a23bcb286c85428ee230',
    messagingSenderId: '1070806981009',
    projectId: 'olmx-d3797',
    authDomain: 'olmx-d3797.firebaseapp.com',
    storageBucket: 'olmx-d3797.appspot.com',
    measurementId: 'G-E709BZPYTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWI7X1_bSdGlFzY1LT6jMOnrKVCmR2WWg',
    appId: '1:1070806981009:android:a9736d4e38fb2e828ee230',
    messagingSenderId: '1070806981009',
    projectId: 'olmx-d3797',
    storageBucket: 'olmx-d3797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdlbOlCysUhlqX45jO3pouO93TC3fvzY',
    appId: '1:1070806981009:ios:510ab4145296dd1c8ee230',
    messagingSenderId: '1070806981009',
    projectId: 'olmx-d3797',
    storageBucket: 'olmx-d3797.appspot.com',
    iosClientId: '1070806981009-dfdtss7fj59i5jvse2vtrh7333303f6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.olmxProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdlbOlCysUhlqX45jO3pouO93TC3fvzY',
    appId: '1:1070806981009:ios:510ab4145296dd1c8ee230',
    messagingSenderId: '1070806981009',
    projectId: 'olmx-d3797',
    storageBucket: 'olmx-d3797.appspot.com',
    iosClientId: '1070806981009-dfdtss7fj59i5jvse2vtrh7333303f6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.olmxProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3m9XSqBhyo8x5bgUAytQOKVFlUmhStKY',
    appId: '1:1070806981009:web:d1624cf672e8d9498ee230',
    messagingSenderId: '1070806981009',
    projectId: 'olmx-d3797',
    authDomain: 'olmx-d3797.firebaseapp.com',
    storageBucket: 'olmx-d3797.appspot.com',
    measurementId: 'G-3ETXTZZRGH',
  );
}
